version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 615299769322.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t more-flask-app .
      - docker tag more-flask-app:latest 615299769322.dkr.ecr.us-east-1.amazonaws.com/more-flask-app:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push 615299769322.dkr.ecr.us-east-1.amazonaws.com/more-flask-app:latest
artifacts:
  files: []
